[2025-08-03T22:57:04.983+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-03T22:57:05.002+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T15:57:03.826609+00:00 [queued]>
[2025-08-03T22:57:05.012+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T15:57:03.826609+00:00 [queued]>
[2025-08-03T22:57:05.012+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-03T22:57:05.034+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-08-03 15:57:03.826609+00:00
[2025-08-03T22:57:05.040+0700] {standard_task_runner.py:63} INFO - Started process 196 to run task
[2025-08-03T22:57:05.043+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stress_level_detection_pipeline', 'preprocess_data', 'manual__2025-08-03T15:57:03.826609+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stress_detection_dag.py', '--cfg-path', '/tmp/tmpkfffp7uo']
[2025-08-03T22:57:05.046+0700] {standard_task_runner.py:91} INFO - Job 2: Subtask preprocess_data
[2025-08-03T22:57:05.123+0700] {task_command.py:426} INFO - Running <TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T15:57:03.826609+00:00 [running]> on host 266eb5332594
[2025-08-03T22:57:05.200+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stress_level_detection_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T15:57:03.826609+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T15:57:03.826609+00:00'
[2025-08-03T22:57:05.202+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-03T22:57:05.253+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-03T22:57:05.254+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stress_detection_dag.py", line 12, in preprocess_data
    df = pd.read_excel(input_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1563, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1419, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/raw_data.xlsx'
[2025-08-03T22:57:05.276+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stress_level_detection_pipeline, task_id=preprocess_data, run_id=manual__2025-08-03T15:57:03.826609+00:00, execution_date=20250803T155703, start_date=20250803T155705, end_date=20250803T155705
[2025-08-03T22:57:05.294+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task preprocess_data ([Errno 2] No such file or directory: '/opt/airflow/data/raw_data.xlsx'; 196)
[2025-08-03T22:57:05.338+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-03T22:57:05.350+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-03T22:57:05.356+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
