[2025-08-03T22:16:58.392+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-03T22:16:58.410+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T15:16:56.560996+00:00 [queued]>
[2025-08-03T22:16:58.417+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T15:16:56.560996+00:00 [queued]>
[2025-08-03T22:16:58.418+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-03T22:16:58.429+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-08-03 15:16:56.560996+00:00
[2025-08-03T22:16:58.433+0700] {standard_task_runner.py:63} INFO - Started process 196 to run task
[2025-08-03T22:16:58.436+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stress_level_detection_pipeline', 'preprocess_data', 'manual__2025-08-03T15:16:56.560996+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stress_detection_dag.py', '--cfg-path', '/tmp/tmpv1ugbqhw']
[2025-08-03T22:16:58.438+0700] {standard_task_runner.py:91} INFO - Job 2: Subtask preprocess_data
[2025-08-03T22:16:58.498+0700] {task_command.py:426} INFO - Running <TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T15:16:56.560996+00:00 [running]> on host f61760fff24c
[2025-08-03T22:16:58.565+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stress_level_detection_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T15:16:56.560996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T15:16:56.560996+00:00'
[2025-08-03T22:16:58.566+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-03T22:16:58.601+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-03T22:16:58.601+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stress_detection_dag.py", line 12, in preprocess_data
    df = pd.read_csv(input_path)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/raw_data.csv'
[2025-08-03T22:16:58.620+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stress_level_detection_pipeline, task_id=preprocess_data, run_id=manual__2025-08-03T15:16:56.560996+00:00, execution_date=20250803T151656, start_date=20250803T151658, end_date=20250803T151658
[2025-08-03T22:16:58.629+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task preprocess_data ([Errno 2] No such file or directory: '/opt/airflow/data/raw_data.csv'; 196)
[2025-08-03T22:16:58.649+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-03T22:16:58.660+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-03T22:16:58.662+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
